### ISSUE TITLE
[storybook] NFT swap confirmation

### ISSUE THREAD

**Issue by tkmct** [zkopru-network/zkopru-extension#43]
adopt swap confirmation to support swapping NFT with FT

**Comment by thebeyondr** [comment]
Ignore that previous PR. What else should be here @tkmct ? 
| <img width="347" alt="image" src="https://user-images.githubusercontent.com/19380973/207405960-c418b0ed-33b4-4b82-a94a-6e69c0785d3d.png"> |
 | -- |
 | Shows NFT data and what you receive. Should this be a request screen though?  |
 
I'm thinking this might be multiple screens actually. 
- Request for swap (how does the other person know you initiated a trade btw?)
- Asset approval (yes they're willing to swap)
- Actual confirm swap on both parties

**Comment by tkmct** [comment]
IMO, swap requests should be done in application side. When both parties agree on the swap, application should call extension API to sign swap transaction in this screen. So I think we don't need request for swap screen and asset approval screens in extension.

I think address of counter party and maybe NFT token id or token name are good info to have in this screen!
